Reapply "media: ov5640: Use runtime PM"
This reverts commit 51cf132302ae7e53227a7074110710acb72efc81.

This revert is needed to avoid camera preview issue on DART-MX95
with the following errors:

  root@imx95-var-dart:~# gst-launch-1.0 v4l2src device=/dev/video0 ! video/x-raw,width=${width},height=${heigth} ! autovideosink sync=false
  Setting pipeline to PAUSED ...
  Pipeline is live and does not need PREROLL ...
  Pipeline is PREROLLED ...
  Setting pipeline to PLAYING ...
  New clock: GstSystemClock
  ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0: Failed to allocate required memory.
  Additional debug info:
  /usr/src/debug/gstreamer1.0-plugins-good/1.24.0.imx/sys/v4l2/gstv4l2src.c(955): gst_v4l2src_decide_allocation (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
  Buffer pool activation failed
  Execution ended after 0:00:00.020982771
  Setting pipeline to NULL ...
  ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0: Internal data stream error.
  Additional debug info:
  /usr/src/debug/gstreamer1.0/1.24.0.imx/libs/gst/base/gstbasesrc.c(3175): gst_base_src_loop (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
  streaming stopped, reason not-negotiated (-4)
  Freeing pipeline ...