imx95-var-dart: fix Bluetooth
- Fixed btnxpuart driver not probed due to BT_ENABLE was busy because used
  in the wifi usdhc3_pwrseq  node.

- Fixed hci0 communication by drop fw-init-baudrate property and avoid the
  following errors:
  [   37.257704] Bluetooth: hci0: Opcode 0x0c03 failed: -110
  [   39.291436] Bluetooth: hci0: Setting wake-up method failed (-110)
  Error: Bluetooth MAC address is 00:00:00:00:00:00

Signed-off-by: FrancescoFerraro <francesco.f@variscite.com>